"""add cities.region

Revision ID: 1b97ca67bc0b
Revises: 9f4cd28a1016
Create Date: 2026-06-10 10:57:06.037719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b97ca67bc0b'
down_revision: Union[str, Sequence[str], None] = '9f4cd28a1016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cities', sa.Column('region', sa.String(), nullable=True))
    op.create_index(op.f('ix_cities_region'), 'cities', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_region'), table_name='cities')
    op.drop_column('cities', 'region')
    # ### end Alembic commands ###
