"""initial schema

Revision ID: 9f4cd28a1016
Revises: 
Create Date: 2026-06-09 22:07:46.784115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f4cd28a1016'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('base_lat', sa.Float(), nullable=False),
    sa.Column('base_lon', sa.Float(), nullable=False),
    sa.Column('base_name', sa.String(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('has_transit', sa.Boolean(), nullable=False),
    sa.Column('transit_operator', sa.String(), nullable=True),
    sa.Column('default_depart', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('matrix_cache',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('city_slug', sa.String(), nullable=True),
    sa.Column('profile', sa.String(), nullable=True),
    sa.Column('matrix', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_matrix_cache_city_slug'), 'matrix_cache', ['city_slug'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_slug', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('locks', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_slug'], ['cities.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_city_slug'), 'plans', ['city_slug'], unique=False)
    op.create_table('pois',
    sa.Column('city_slug', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('dwell_min', sa.Integer(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('hours', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['city_slug'], ['cities.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('city_slug', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pois')
    op.drop_index(op.f('ix_plans_city_slug'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_matrix_cache_city_slug'), table_name='matrix_cache')
    op.drop_table('matrix_cache')
    op.drop_table('cities')
    # ### end Alembic commands ###
